// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"clickToMovePlugin","status":true,"description":"Toggle Enable/Disable touch movement on map.","parameters":{}}
];
